backend:
  name: github
  repo: YOUR-USERNAME/YOUR-REPOSITORY
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:

  - name: "blogs"
    label: "Blogs"
    folder: "content/blogs"
    create: true

  - name: "certifications"
    label: "Certifications"
    folder: "content/certifications"
    create: true
